export const AUTHENTICATE_USER_IN_PROGRESS = 'AUTHENTICATE_USER_IN_PROGRESS';
export const AUTHENTICATE_USER_FAILED = 'AUTHENTICATE_USER_FAILED';
export const AUTHENTICATE_USER_COMPLETED = 'AUTHENTICATE_USER_COMPLETED';
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const REGISTER_USER_IN_PROGRESS = 'REGISTER_USER_IN_PROGRESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';
export const REGISTER_USER_COMPLETED = 'REGISTER_USER_COMPLETED';
export const SIGN_OUT = 'SIGN_OUT';
export const ORDER_CONFIRMED = 'ORDER_CONFIRMED';

export const ADD_OR_INCREMENT_PRODUCT_IN_CART = 'ADD_OR_INCREMENT_PRODUCT_IN_CART';
export const REMOVE_OR_DECREMENT_PRODUCT_IN_CART = 'REMOVE_OR_DECREMENT_PRODUCT_IN_CART';
export const CLEAR_CART = 'CLEAR_CART';
