export const AUTHENTICATE_USER_REQUEST = 'AUTHENTICATE_USER_REQUEST';
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_FAILED = 'AUTHENTICATE_USER_FAILED';
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';
export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST';
export const ORDER_CONFIRMED = 'ORDER_CONFIRMED';

export const ADD_PRODUCT_IN_CART = 'ADD_PRODUCT_IN_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';

export const ADD_FILTER = 'ADD_FILTER';
export const CLEAR_FILTER = 'REMOVE_FILTER';
